name: Run Potter Test
g
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Run tests with unittest
        run: python3 -m unittest 